import json
from pathlib import Path

from audit_logger import append_audit_log


SUGGESTIONS_PATH = Path("data/ai_suggestions.json")
DECISIONS_PATH = Path("data/decisions.json")


VALID_DECISIONS = {
    "1": "Accepted",
    "2": "Rejected",
    "3": "Partially accepted",
    "4": "Needs human review"
}


def load_suggestions(path: Path = SUGGESTIONS_PATH) -> list[dict]:
    """
    Loads AI suggestions generated by ai_reviewer.py.
    """
    if not path.exists():
        raise FileNotFoundError(
            "No AI suggestions found. Run: python app/ai_reviewer.py sample_project/auth.py"
        )

    return json.loads(path.read_text(encoding="utf-8"))


def save_decisions(decisions: list[dict], path: Path = DECISIONS_PATH) -> None:
    """
    Saves all human decisions to a JSON file.
    """
    path.parent.mkdir(parents=True, exist_ok=True)

    path.write_text(
        json.dumps(decisions, indent=4, ensure_ascii=False),
        encoding="utf-8"
    )


def ask_human_decision(suggestion: dict, responsible: str) -> dict:
    """
    Asks the human reviewer to evaluate one AI suggestion.
    """
    print("\n" + "=" * 80)
    print(f"Suggestion ID: {suggestion['id']}")
    print(f"Title: {suggestion['title']}")
    print(f"Category: {suggestion['category']}")
    print(f"Risk: {suggestion['risk']}")
    print("\nDescription:")
    print(suggestion["description"])
    print("\nRecommendation:")
    print(suggestion["recommendation"])

    print("\nHuman decision:")
    print("1 - Accepted")
    print("2 - Rejected")
    print("3 - Partially accepted")
    print("4 - Needs human review")

    choice = input("\nChoose an option: ").strip()

    while choice not in VALID_DECISIONS:
        print("Invalid option. Choose 1, 2, 3 or 4.")
        choice = input("Choose an option: ").strip()

    justification = input("Write a short justification: ").strip()

    while not justification:
        print("Justification is required for accountability.")
        justification = input("Write a short justification: ").strip()

    decision_entry = {
        "suggestion_id": suggestion["id"],
        "category": suggestion["category"],
        "risk": suggestion["risk"],
        "title": suggestion["title"],
        "human_decision": VALID_DECISIONS[choice],
        "justification": justification,
        "responsible": responsible,
        "human_validation_required": suggestion["human_validation_required"]
    }

    append_audit_log(decision_entry)

    return decision_entry


def main():
    suggestions = load_suggestions()

    print("\nCollabQA — Human Decision Layer")
    print("AI suggestions must be validated by a human reviewer.\n")

    responsible = input("Responsible reviewer name: ").strip()

    while not responsible:
        print("Responsible reviewer name is required.")
        responsible = input("Responsible reviewer name: ").strip()

    decisions = []

    for suggestion in suggestions:
        decision = ask_human_decision(suggestion, responsible)
        decisions.append(decision)

    save_decisions(decisions)

    print("\nHuman decisions saved to data/decisions.json")
    print("Audit log updated at data/audit_log.csv")


if __name__ == "__main__":
    main()